### ISSUE TITLE
not enough values to unpack

### ISSUE THREAD

**Issue by milansoliya4210** [martinzlocha/anchor-optimization#10]
Give me this error
`Using TensorFlow backend.
Loading object dimensions.
Traceback (most recent call last):
  File "anchor-optimization/optimize_anchors.py", line 131, in <module>
    x1, y1, x2, y2 = list(map(lambda x: int(x), row[1:5]))
ValueError: not enough values to unpack (expected 4, got 1)`

**Comment by martinzlocha** [comment]
Seems like you are not imputing the files in the right format because `row[1:5]` only returns one value, it should be returning 4. Please have a look at keras-retinanet to see the correct CSV format.
