### ISSUE TITLE
GET LOTTA RESULTS 

### ISSUE THREAD

**Issue by qtw1998** [martinzlocha/anchor-optimization#14]
![](https://site-pictures.oss-eu-west-1.aliyuncs.com/rw6xs.png)
which one is the final result? I'm so obfuscated..

**Comment by casimp** [comment]
If you wait long enough then the 'Final best anchor configuration' will be returned. In general, you are looking for a result that minimizes the number of labels that don't have any matching anchors.

**Comment by martinzlocha** [comment]
Yes, @casimp is right, just have to give this some time, mainly if you have many examples.
