### ISSUE TITLE
anchors optimisation stuck at 39000 anchors left.

### ISSUE THREAD

**Issue by MaleshwarSastri** [martinzlocha/anchor-optimization#17]
Current best anchor configuration
Ratios: [0.401, 1.0, 2.497]
Scales: [0.747, 1.103, 1.398]
Number of labels that don't have any matching anchor: 56047

Current best anchor configuration
Ratios: [0.355, 1.0, 2.816]
Scales: [0.582, 1.541, 1.873]
Number of labels that don't have any matching anchor: 51863

Current best anchor configuration
Ratios: [0.29, 1.0, 3.453]
Scales: [0.931, 0.99, 1.056]
Number of labels that don't have any matching anchor: 46175

Current best anchor configuration
Ratios: [0.254, 1.0, 3.944]
Scales: [0.867, 1.148, 1.549]
Number of labels that don't have any matching anchor: 39772

Current best anchor configuration
Ratios: [0.251, 1.0, 3.99]
Scales: [0.818, 0.994, 1.783]
Number of labels that don't have any matching anchor: 39665

Current best anchor configuration
Ratios: [0.251, 1.0, 3.99]
Scales: [0.994, 1.246, 1.387]
Number of labels that don't have any matching anchor: 39424

Current best anchor configuration
Ratios: [0.251, 1.0, 3.981]
Scales: [0.853, 1.29, 1.382]
Number of labels that don't have any matching anchor: 40024

Current best anchor configuration
Ratios: [0.251, 1.0, 3.978]
Scales: [1.113, 1.289, 1.713]
Number of labels that don't have any matching anchor: 39559

Current best anchor configuration
Ratios: [0.251, 1.0, 3.991]
Scales: [0.812, 1.37, 1.965]
Number of labels that don't have any matching anchor: 39546

Current best anchor configuration
Ratios: [0.25, 1.0, 3.998]
Scales: [0.824, 1.232, 1.781]
Number of labels that don't have any matching anchor: 39590

Current best anchor configuration
Ratios: [0.25, 1.0, 3.994]
Scales: [0.605, 1.048, 1.64]
Number of labels that don't have any matching anchor: 39333

Current best anchor configuration
Ratios: [0.25, 1.0, 3.995]
Scales: [0.747, 1.004, 1.219]
Number of labels that don't have any matching anchor: 39350
===============
 this was the best anchor configuration i've got and i used --no-resize with image of size 1500*1500. how do i obtain better results without and dataset is huge to use --include-stride.

**Comment by martinzlocha** [comment]
You could potentially try increasing the bounds (https://github.com/martinzlocha/anchor-optimization/blob/master/optimize_anchors.py#L171) on the ratios and using 5 ratios instead of 3. Seems like your objects are very long and narrow so that might help. 

However if you change the bounds I would recommend using --include-stride and potentially reduce the number of samples so that it runs quicker.

**Comment by MaleshwarSastri** [comment]
Sorry for the late reply.Thanks a lot man. Appreciate it.

**Comment by ChunmianLin** [comment]
> Sorry for the late reply.Thanks a lot man. Appreciate it.
Hi, how much time do you observe the best/final result?
I have taken two more hours, but I don't know which result is the best?
Please help me! Thanks!

**Comment by ChunmianLin** [comment]
Also, I confuse about  'Number of labels that don't have any matching anchor: 39333'. Does the larger value mean the best anchor result?
