### ISSUE TITLE
output

### ISSUE THREAD

**Issue by ChunmianLin** [martinzlocha/anchor-optimization#18]
Hi, when I run the script, the output always shows this information as follows:
![Screenshot from 2020-07-08 16-06-58](https://user-images.githubusercontent.com/53289159/86894105-2c5de580-c135-11ea-9e1e-3fe14ff85cea.png)

I don't know how to do next. It seems not to be the desired anchor result regarding our own data?
Please help me! 
Thanks!

**Comment by ChunmianLin** [comment]
![Screenshot from 2020-07-08 17-07-30](https://user-images.githubusercontent.com/53289159/86900142-8d89b700-c13d-11ea-9089-832e541656a3.png)
The error occurs when I use --include_stride.
How can do I next?

**Comment by ChunmianLin** [comment]
BTW, if I just the command '**python optimize_anchors.py PATH_TO_CSV --ratios=5 --no-resize**‘, how much time should I wait for the final optimization result?
Actually, it takes me two hours, but I couldn't observe the final result. For DE algorithm, the parameter 'maxiter' is just 50. So, I want to how much time you spend to get your anchor optimization result, as demonstrated in your paper?

Thanks in advance! And I would appreciate a lot if you provide me any help!

**Comment by martinzlocha** [comment]
Hi, the optimisation takes several hours, if you want quicker results maybe sample the dataset. With regards to your first issue I assume that it's because you are using python2 but I am not sure, that's not the expected output.

**Comment by martinzlocha** [comment]
I think the issue which was mentioned in the first comment should now be resolved. Feel free to reopen if you have anything else.
