### ISSUE TITLE
Tensorflow-gpu

### ISSUE THREAD

**Issue by nicholasguimaraes** [martinzlocha/anchor-optimization#5]
Hi guys, for the requirements I see you are using tensorflow rather than tensorflow-gpu.

I have tensorflow-gpu installed. Can I remove tensorflow from the requirements to be downloaded and run the code normally?

**Comment by martinzlocha** [comment]
Hi, yes you can remove it. I don't even think that tensorflow is required at all (other than by keras-retinanet) so maybe it would be best to remove it all together if everything runs fine without it.

**Comment by martinzlocha** [comment]
Closing the issue do to inactivity. If you have any other questions let me know.
