### ISSUE TITLE
an puzzle on --no-resize

### ISSUE THREAD

**Issue by 2696120622** [martinzlocha/anchor-optimization#9]
Which value of --no-resize will give a better result, True of False?
It looks like that True (i.e. resizing the bounding box) is better.

**Comment by martinzlocha** [comment]
It is not as simple as saying that one is better than the other option. It depends on the sizes of your images, sizes of your boxes etc.

Also you should only use the option if you also train your keras-retinanet model with --no-resize.

**Comment by 2696120622** [comment]
Thanks.
However, the default state in martinzlocha/anchor-optimization  is different from the default state fizyr/keras-retinanet.
in martinzlocha/anchor-optimization
parser.add_argument('--no-resize', help='Disable image resizing.', dest='resize', action='store_false')

in fizyr/keras-retinanet,
parser.add_argument('--no-resize',        help='Don''t rescale the image.', action='store_true')

**Comment by martinzlocha** [comment]
Both for anchor-optimization and for keras-retinanet if you don't provide any arguments the images will be resized. Yes one implementation uses store_true and the second uses store_false but thats just an underlying implementational detail. In this codebase `if resize` is true then the image will be resized, in keras-retinanet `if not no_resize` is true then the image will be resized.

I hope this makes sense. I just wanted to avoid a double negation.

**Comment by 2696120622** [comment]
Tnanks.
I get it.
